pipelines:
  branches:
   main:
    - step: 
        name: Deploy to production
        deployment: production
        script:
          - pipe: microsoft/azure-static-web-apps-deploy:main
            variables:
                APP_LOCATION: '$BITBUCKET_CLONE_DIR/'
                OUTPUT_LOCATION: '$$BITBUCKET_CLONE_DIR/'
                API_TOKEN: $deployment_token
